#!/usr/bin/env bash
# set up ufw in order to block incoming traffic except the next openssh

ufw status verbose
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp
ufw enable